## 以下是用pandas

In [1]:
import numpy
from numpy import matrix
import pandas as pd

In [2]:
logs = pd.read_csv('./onlydrink_meal_range500.csv',header=None)

In [3]:
logs

0    1    2    3    4    5    6    7    8    9   ...   542  543  544  \
0      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
1      0    0    0    0    0    0    0    1    0    0 ...     0    0    0   
2      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
3      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
4      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
5      0    0    1    0    0    0    0    0    0    0 ...     0    0    0   
6      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
7      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
8      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
9      0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
10     0    0    0    0    0    0    0    0    0    1 ...     0    0    0   
11     0    0    1    0    0    0    0    0    0    0 ...     0    0    0   
12     0    0    1    0    0    0    0    0    0    0 ...     0    0    0   
13     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
14     0    0    1    0    0    0    0    0    0    0 ...     0    0    0   
15     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
16     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
17     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
18     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
19     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
20     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
21     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
22     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
23     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
24     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
25     0    0    0    0    1    0    0    0    0    0 ...     0    0    0   
26     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
27     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
28     0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
29     1    0    0    0    0    0    0    0    0    0 ...     0    0    0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
114    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
115    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
116    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
117    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
118    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
119    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
120    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
121    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
122    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
123    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
124    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
125    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
126    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
127    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
128    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
129    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
130    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
131    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
132    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
133    0    0    0    0    0    0    0    0    0    0 ...     0    0    0   
1

In [4]:
restaurants = logs.index.tolist()

In [5]:
len(restaurants)

144

In [6]:
tags = list(logs.columns.values)

In [7]:
len(tags)

552

In [8]:
graph = numpy.matrix(logs)

In [9]:
graph

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
restaurant_sim = matrix(numpy.identity(len(restaurants)))

In [11]:
restaurant_sim 

matrix([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  1.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [12]:
tag_sim = matrix(numpy.identity(len(tags)))

In [13]:
tag_sim 

matrix([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  1.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [14]:
# 計算兩個子集分別有多少種類
def get_tags_num(restaurant):
    r_i = restaurants.index(restaurant)
    return graph[r_i]

def get_restaurants_num(tag):
    t_j = tags.index(tag)
    return graph.transpose()[t_j]

In [15]:
#讓子集種類依照順序排序?
def get_tags(restaurant):
    series = get_tags_num(restaurant).tolist()[0]
    return [ tags[x] for x in range(len(series)) if series[x] > 0 ]

def get_restaurants(tag):
    series = get_restaurants_num(tag).tolist()[0]
    return [ restaurants[x] for x in range(len(series)) if series[x] > 0 ]

In [16]:
# 找到restaurant子集的相似度
def restaurant_simrank(r1, r2, C):
    """
    in this, graph[r_i] -> connected tags
    """
    """
    print "r1.tags"
    print get_tags_num(r1).tolist()
    print "r2.tags"
    print get_tags_num(r2).tolist()
    """
    if r1 == r2 : return 1
    prefix = C / (get_tags_num(r1).sum() * get_tags_num(r2).sum())
    postfix = 0
    for tag_i in get_tags(r1):
        for tag_j in get_tags(r2):
            i = tags.index(tag_i)
            j = tags.index(tag_j)
            postfix += tag_sim[i, j]
    return prefix * postfix

In [17]:
# 找到tag 子集的相似度
def tag_simrank(t1, t2, C):
    """
    in this, graph need to be transposed to make ad to be the index
    """
    """
    print "t1.restaurants"
    print get_restaurants_num(t1)
    print "t2.restaurants"
    print get_restaurants_num(t2)
    """
    if t1 == t2 : return 1
    prefix = C / (get_restaurants_num(t1).sum() * get_restaurants_num(t2).sum())
    postfix = 0
    for restaurant_i in get_restaurants(t1):
        for restaurant_j in get_restaurants(t2):
            i = restaurants.index(restaurant_i)
            j = restaurants.index(restaurant_j)
            postfix += restaurant_sim[i,j]
    return prefix * postfix

In [32]:
#依照兩個子集的相似度定義出新的相似度矩陣
def simrank(C=0.8, times=50):
    global restaurant_sim, tag_sim

    for run in range(times):
        # restaurants simrank
        new_restaurant_sim = matrix(numpy.identity(len(restaurants)))
        for ri in restaurants:
            for rj in restaurants:
                i =  restaurants.index(ri)
                j =  restaurants.index(rj)
                new_restaurant_sim[i,j] = restaurant_simrank(ri, rj, C)


        # tags simrank
        new_tag_sim = matrix(numpy.identity(len(tags)))
        for ti in tags:
            for tj in tags:
                i = tags.index(ti)
                j = tags.index(tj)
                new_tag_sim[i,j] = tag_simrank(ti, tj, C)

        restaurant_sim = new_restaurant_sim
        tag_sim = new_tag_sim

In [ ]:
if __name__ == '__main__':
#     print("========================restaurants=========================")
#     print (restaurants[0])
#     print("========================tags============================")
#     print (tags)
    simrank()
    print("========================restaurant_sim======================")
    print (restaurant_sim)
    print("========================tag_sim=========================")
    print (tag_sim)

In [ ]:
restaurant_sim

In [ ]:
tmp = pd.DataFrame(restaurant_sim)

In [ ]:
pd.DataFrame.to_csv(tmp)

In [ ]:
tmp.to_csv('./drink_meal50.csv')