In [1]:
import numpy
from numpy import matrix
import csv

In [2]:
with open ('./tag_matrix.csv') as f:
    logs = f.readlines()

In [3]:
graph = numpy.matrix(logs).astype(numpy.int)

ValueError: invalid literal for int() with base 10: '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,7

In [ ]:
restaurants = [row for row in logs[1:]]

In [ ]:
len(restaurants)

In [ ]:
restaurants0 = logs[0]

In [33]:
restaurants.

pandas.core.frame.DataFrame

In [ ]:
tags = restaurants0.split(',')

In [ ]:
type(tags)

In [ ]:
len(tags)

## 以下是用pandas

In [155]:
import numpy
from numpy import matrix
import pandas as pd

In [156]:
logs = pd.read_csv('./tag_matrix_1.csv',header=None)

In [154]:
logs

0      1      2      3      4      5      6      7      8      9      \
0         1      2      3      4      5      6      7      8      9     10   
1         1      0      0      0      0      0      0      0      0      0   
2         0      1      0      0      0      0      0      0      0      0   
3         0      0      1      0      0      0      0      0      0      0   
4         0      0      0      1      0      0      0      0      0      0   
5         0      0      0      0      1      0      0      0      0      0   
6         0      0      0      0      0      1      0      0      0      0   
7         0      0      0      0      0      0      1      0      0      0   
8         1      0      0      0      0      0      0      1      0      0   
9         0      0      0      0      0      0      0      0      1      0   
10        0      0      0      0      0      0      0      0      0      1   
11        0      0      0      0      0      0      0      0      0      0   
12        0      0      0      0      0      0      0      0      0      0   
13        0      0      0      0      0      0      0      0      0      0   
14        0      0      0      0      0      1      0      0      0      0   
15        0      0      0      0      0      0      0      0      0      0   
16        0      0      0      0      0      1      1      0      0      0   
17        0      0      0      0      0      0      0      0      0      0   
18        0      0      0      0      0      0      0      0      0      0   
19        0      0      0      0      0      0      0      0      0      0   
20        0      0      0      0      0      1      0      0      0      0   
21        0      0      0      0      0      0      0      0      0      0   
22        0      0      0      0      0      1      0      0      0      0   
23        0      0      0      0      0      0      0      0      0      0   
24        0      0      0      0      0      0      0      0      0      0   
25        0      0      0      0      0      0      0      0      0      0   
26        0      0      0      0      0      0      0      0      0      0   
27        0      0      0      0      0      0      0      0      0      0   
28        0      0      0      0      0      0      0      0      0      0   
29        0      0      0      0      0      0      0      0      0      0   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
5188      0      0      0      0      0      0      0      0      0      0   
5189      0      0      0      0      0      0      0      0      0      0   
5190      0      0      0      0      0      0      0      0      0      0   
5191      0      0      0      0      0      0      0      0      0      0   
5192      0      0      0      0      0      0      0      0      0      0   
5193      0      0      0      0      0      1      0      0      0      0   
5194      0      0      0      0      0      0      0      0      0      0   
5195      0      0      0      0      0      0      0      0      0      0   
5196      0      0      0      0      0      0      0      0      0      0   
5197      0      0      0      0      0      0      0      0      0      0   
5198      0      0      0      0      0      0      0      0      0      0   
5199      0      0      0      0      0      0      0      0      0      0   
5200      0      0      0      0      0      0      0      0      0      0   
5201      0      0      0      0      0      0      0      0      0      0   
5202      0      0      0      0      0      0      0      0      0      0   
5203      1      0      0      0      0      0      0      0      0      0   
5204      0      0      0      0      0      0      0      0      0      0   
5205      0      0      0      0      0      0      0      0      0      0   
5206      0      0      0      0      0      0      0      0      0      0   
5207      0      0      0   

In [160]:
restaurants = logs.index.tolist()

In [166]:
len(restaurants)

5217

In [171]:
tags = list(logs.columns.values)

In [173]:
len(tags)

10347

In [174]:
graph = numpy.matrix(numpy.zeros([len(restaurants), len(tags)]))

In [175]:
graph

matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [176]:
restaurant_sim = matrix(numpy.identity(len(restaurants)))

In [177]:
restaurant_sim 

matrix([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  1.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [178]:
tag_sim = matrix(numpy.identity(len(tags)))

In [179]:
tag_sim 

matrix([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  1.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  1.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [180]:
# 計算兩個子集分別有多少種類
def get_tags_num(restaurant):
    r_i = restaurants.index(restaurant)
    return graph[r_i]

def get_restaurants_num(tag):
    t_j = tags.index(tag)
    return graph.transpose()[t_j]

In [181]:
#讓子集種類依照順序排序?
def get_tags(restaurant):
    series = get_tags_num(restaurant).tolist()[0]
    return [ tags[x] for x in range(len(series)) if series[x] > 0 ]

def get_restaurants(tag):
    series = get_restaurants_num(tag).tolist()[0]
    return [ restaurants[x] for x in range(len(series)) if series[x] > 0 ]

In [182]:
# 找到restaurant子集的相似度
def restaurant_simrank(r1, r2, C):
    """
    in this, graph[r_i] -> connected tags
    """
    """
    print "r1.tags"
    print get_tags_num(r1).tolist()
    print "r2.tags"
    print get_tags_num(r2).tolist()
    """
    if r1 == r2 : return 1
    prefix = C / (get_tags_num(r1).sum() * get_tags_num(r2).sum())
    postfix = 0
    for tag_i in get_tags(r1):
        for tag_j in get_tags(r2):
            i = tags.index(tag_i)
            j = tags.index(tag_j)
            postfix += tag_sim[i, j]
    return prefix * postfix

In [183]:
# 找到tag 子集的相似度
def tag_simrank(t1, t2, C):
    """
    in this, graph need to be transposed to make ad to be the index
    """
    """
    print "t1.restaurants"
    print get_restaurants_num(t1)
    print "t2.restaurants"
    print get_restaurants_num(t2)
    """
    if t1 == t2 : return 1
    prefix = C / (get_restaurants_num(t1).sum() * get_restaurants_num(t2).sum())
    postfix = 0
    for restaurant_i in get_restaurants(t1):
        for restaurant_j in get_restaurants(t2):
            i = restaurants.index(restaurant_i)
            j = restaurants.index(restaurant_j)
            postfix += restaurant_sim[i,j]
    return prefix * postfix

In [184]:
#依照兩個子集的相似度定義出新的相似度矩陣
def simrank(C=0.8, times=1):
    global restaurant_sim, tag_sim

    for run in range(times):
        # restaurants simrank
        new_restaurant_sim = matrix(numpy.identity(len(restaurants)))
        for ri in restaurants:
            for rj in restaurants:
                i =  restaurants.index(ri)
                j =  restaurants.index(rj)
                new_restaurant_sim[i,j] = restaurant_simrank(ri, rj, C)


        # tags simrank
        new_tags_sim = matrix(numpy.identity(len(tags)))
        for ti in tags:
            for tj in tags:
                i = tags.index(ai)
                j = tags.index(aj)
                new_tag_sim[i,j] = tag_simrank(ti, tj, C)

        restaurant_sim = new_restaurant_sim
        tag_sim = new_tag_sim

In [ ]:
if __name__ == '__main__':
#     print("========================restaurants=========================")
#     print (restaurants[0])
#     print("========================tags============================")
#     print (tags)
    simrank()
    print("========================restaurant_sim======================")
    print (restaurant_sim)
#     print("========================tag_sim=========================")
#     print (tag_sim)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in double_scalars
  del sys.path[0]
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:20: RuntimeWarning: invalid value encountered in double_scalars
